### PR TITLE
Fix lookup in formPopup.comp.tsx to work with json objects

### LINKED ISSUE #142: 'object' fields are not being rendered if dataPath is set in config.json
I have a put config like this:

```
"put": {
          "url": "<some_url>",
          "includeOriginalFields": true,
          "fields": [
            {
              "name": "payload",
              "type": "object",
              "label": "payload",
              "dataPath": "payload"
            }
          ]
        },
```

The object coming from the REST api looks like this:

```json
{
    "external_id": "str",
    "payload": {
         "payload": <some json here>
    }
}
```

This is the resulting form:

image

When I remove the dataPath it works, but obviously displays the wrong data.

### PR DESCRIPTION
**Pull request by s4ke**
fixes #142

### CODE REVIEW

**Comment by s4ke** [comment]
requires #141 to be merged first

**Comment by s4ke** [comment]
requires #141 to be merged first.

**Comment by s4ke** [comment]
Hey,

I thought that #141 would be merged before this, so I branched off my current development state since I am testing everything against my REST API. If #141 is okay I would suggest we revisit this PR after it is merged?

**Comment by dsternlicht** [comment]
@s4ke no need. All approved :)

**Pull request merged**
