### PR TITLE
config: relative to index.html

### PR DESCRIPTION
**Pull request by Oncilla**
Make config path relative to `index.html`.

This allows serving the project from a non-root path.

---
This change is [Reviewable](https://reviewable.io/reviews/dsternlicht/restool/137)

### CODE REVIEW

**Comment by dsternlicht** [comment]
@Oncilla I'm pretty sure it's going to break a few things.
Can you please validate the settings are being loaded correctly from a remote as well?

**Comment by Oncilla** [comment]
Hi,

What do you mean with settings are being loaded correctly from a remote?

**Comment by dsternlicht** [comment]
Please read the docs on how to load a configuration file into RESTool, and make sure all options work.

**Comment by Oncilla** [comment]
Okay, so here is what I did to verify it works.


1. `npm run build` with the changes proposed in this PR
2. `mv build/config-sample.json build/config.json`
3. Serve `build` directory at `localhost:9000/ui` (`go run main.go` on the snippet posted below)

This results in the UI working as expected, and hello endpoint is also accessible.
If this is not enough testing, please let me know what else I should verify.


Screenshots:
Screenshot from 2020-06-25 19-25-57
Screenshot from 2020-06-25 19-27-05

main.go:
```go
package main

import (
	"log"
	"net/http"
)

func main() {
	// Serve build directory containing config.json etc under '/ui'.
	fs := http.FileServer(http.Dir("./build"))
	http.Handle("/ui/", http.StripPrefix("/ui/", fs))

	// Serve other endpoint.
	http.Handle("/hello", http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		rw.Write([]byte("hello"))
	}))

	err := http.ListenAndServe(":9000", nil)
	log.Fatal(err)
}
```

**Comment by Oncilla** [comment]
@dsternlicht Is there anything I can do to move this forward?

**Comment by dsternlicht** [comment]
@Oncilla I'll try to review and approve by end of week.

**Pull request merged**
